// Code generated by protoc-gen-mutable. DO NOT EDIT.
// source: atframe/etcd.proto

package atframe

import (
	durationpb "google.golang.org/protobuf/types/known/durationpb"
)

import "google.golang.org/protobuf/proto"
import "log/slog"
import pu "github.com/atframework/atframe-utils-go/proto_utility"
import lu "github.com/atframework/atframe-utils-go/lang_utility"
import protoreflect "google.golang.org/protobuf/reflect/protoreflect"

type innerFile_atframe_etcd_protoReadonlyMessage interface {
	Descriptor() protoreflect.MessageDescriptor
	Type() protoreflect.MessageType
	New() protoreflect.Message
	Interface() protoreflect.ProtoMessage
	Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool)
	Has(protoreflect.FieldDescriptor) bool
	Get(protoreflect.FieldDescriptor) protoreflect.Value
	WhichOneof(protoreflect.OneofDescriptor) protoreflect.FieldDescriptor
	GetUnknown() protoreflect.RawFields
	IsValid() bool
}

// ===== Clone methods for RetryConfig ===== Message ====
func (m *RetryConfig) Clone() *RetryConfig {
	if m == nil {
		return new(RetryConfig)
	}
	return proto.Clone(m).(*RetryConfig)
}

// ===== Merge methods for RetryConfig ===== Message ====
func (m *RetryConfig) Merge(src *RetryConfig) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for RetryConfig ===== Message ====
func (m *RetryConfig) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableTextIndent(m))
}

// ===== GetMessageReflectType methods for RetryConfig ===== Message =====
func (_ *RetryConfig) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[RetryConfig]()
}

// ===== Readonly wrapper for RetryConfig ===== Message ====
type Readonly_RetryConfig struct {
	protoData            *RetryConfig
	fieldMaxRetries      int32
	fieldInitialInterval *durationpb.Duration
	fieldMaxInterval     *durationpb.Duration
	fieldBackoff         BackoffType
}

func (r *Readonly_RetryConfig) ReadonlyProtoReflect() innerFile_atframe_etcd_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *RetryConfig) ToReadonly() *Readonly_RetryConfig {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_RetryConfig{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_RetryConfig) CloneMessage() *RetryConfig {
	if r == nil {
		return new(RetryConfig)
	}
	return r.protoData.Clone()
}

func (r *Readonly_RetryConfig) ToMessage() *RetryConfig {
	return r.CloneMessage()
}

func (r Readonly_RetryConfig) LogValue() slog.Value {
	return r.protoData.LogValue()
}

func (r *Readonly_RetryConfig) initFromProto(src *RetryConfig) {
	if r == nil || src == nil {
		return
	}
	r.fieldMaxRetries = src.GetMaxRetries()
	if v := src.GetInitialInterval(); v != nil {
		r.fieldInitialInterval = proto.Clone(v).(*durationpb.Duration)
	} else {
		r.fieldInitialInterval = nil
	}
	if v := src.GetMaxInterval(); v != nil {
		r.fieldMaxInterval = proto.Clone(v).(*durationpb.Duration)
	} else {
		r.fieldMaxInterval = nil
	}
	r.fieldBackoff = src.GetBackoff()
}

func (r *Readonly_RetryConfig) GetMaxRetries() int32 {
	if r == nil {
		var zero int32
		return zero
	}
	return r.fieldMaxRetries
}

func (r *Readonly_RetryConfig) GetInitialInterval() *durationpb.Duration {
	if r == nil {
		var zero *durationpb.Duration
		return zero
	}
	return r.fieldInitialInterval
}

func (r *Readonly_RetryConfig) GetMaxInterval() *durationpb.Duration {
	if r == nil {
		var zero *durationpb.Duration
		return zero
	}
	return r.fieldMaxInterval
}

func (r *Readonly_RetryConfig) GetBackoff() BackoffType {
	if r == nil {
		var zero BackoffType
		return zero
	}
	return r.fieldBackoff
}

// ===== Mutable methods for RetryConfig ===== Message =====
func (m *RetryConfig) MutableInitialInterval() *durationpb.Duration {
	if m.InitialInterval == nil {
		m.InitialInterval = new(durationpb.Duration)
	}
	return m.InitialInterval
}

// ===== Mutable methods for RetryConfig ===== Message =====
func (m *RetryConfig) MutableMaxInterval() *durationpb.Duration {
	if m.MaxInterval == nil {
		m.MaxInterval = new(durationpb.Duration)
	}
	return m.MaxInterval
}

// ===== Clone methods for TLSConfig ===== Message ====
func (m *TLSConfig) Clone() *TLSConfig {
	if m == nil {
		return new(TLSConfig)
	}
	return proto.Clone(m).(*TLSConfig)
}

// ===== Merge methods for TLSConfig ===== Message ====
func (m *TLSConfig) Merge(src *TLSConfig) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for TLSConfig ===== Message ====
func (m *TLSConfig) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableTextIndent(m))
}

// ===== GetMessageReflectType methods for TLSConfig ===== Message =====
func (_ *TLSConfig) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[TLSConfig]()
}

// ===== Readonly wrapper for TLSConfig ===== Message ====
type Readonly_TLSConfig struct {
	protoData               *TLSConfig
	fieldEnabled            bool
	fieldCertFile           string
	fieldKeyFile            string
	fieldCaFile             string
	fieldServerName         string
	fieldInsecureSkipVerify bool
	fieldMinVersion         uint32
	fieldMaxVersion         uint32
	fieldClientAuth         int32
	fieldCipherSuites       string
	fieldCipherSuitesTls13  string
	fieldEnableAlpn         bool
	fieldClientCertType     string
	fieldKeyType            string
	fieldKeyPassword        string
	fieldTlsAuthUsername    string
	fieldTlsAuthPassword    string
}

func (r *Readonly_TLSConfig) ReadonlyProtoReflect() innerFile_atframe_etcd_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *TLSConfig) ToReadonly() *Readonly_TLSConfig {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_TLSConfig{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_TLSConfig) CloneMessage() *TLSConfig {
	if r == nil {
		return new(TLSConfig)
	}
	return r.protoData.Clone()
}

func (r *Readonly_TLSConfig) ToMessage() *TLSConfig {
	return r.CloneMessage()
}

func (r Readonly_TLSConfig) LogValue() slog.Value {
	return r.protoData.LogValue()
}

func (r *Readonly_TLSConfig) initFromProto(src *TLSConfig) {
	if r == nil || src == nil {
		return
	}
	r.fieldEnabled = src.GetEnabled()
	r.fieldCertFile = src.GetCertFile()
	r.fieldKeyFile = src.GetKeyFile()
	r.fieldCaFile = src.GetCaFile()
	r.fieldServerName = src.GetServerName()
	r.fieldInsecureSkipVerify = src.GetInsecureSkipVerify()
	r.fieldMinVersion = src.GetMinVersion()
	r.fieldMaxVersion = src.GetMaxVersion()
	r.fieldClientAuth = src.GetClientAuth()
	r.fieldCipherSuites = src.GetCipherSuites()
	r.fieldCipherSuitesTls13 = src.GetCipherSuitesTls13()
	r.fieldEnableAlpn = src.GetEnableAlpn()
	r.fieldClientCertType = src.GetClientCertType()
	r.fieldKeyType = src.GetKeyType()
	r.fieldKeyPassword = src.GetKeyPassword()
	r.fieldTlsAuthUsername = src.GetTlsAuthUsername()
	r.fieldTlsAuthPassword = src.GetTlsAuthPassword()
}

func (r *Readonly_TLSConfig) GetEnabled() bool {
	if r == nil {
		var zero bool
		return zero
	}
	return r.fieldEnabled
}

func (r *Readonly_TLSConfig) GetCertFile() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldCertFile
}

func (r *Readonly_TLSConfig) GetKeyFile() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldKeyFile
}

func (r *Readonly_TLSConfig) GetCaFile() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldCaFile
}

func (r *Readonly_TLSConfig) GetServerName() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldServerName
}

func (r *Readonly_TLSConfig) GetInsecureSkipVerify() bool {
	if r == nil {
		var zero bool
		return zero
	}
	return r.fieldInsecureSkipVerify
}

func (r *Readonly_TLSConfig) GetMinVersion() uint32 {
	if r == nil {
		var zero uint32
		return zero
	}
	return r.fieldMinVersion
}

func (r *Readonly_TLSConfig) GetMaxVersion() uint32 {
	if r == nil {
		var zero uint32
		return zero
	}
	return r.fieldMaxVersion
}

func (r *Readonly_TLSConfig) GetClientAuth() int32 {
	if r == nil {
		var zero int32
		return zero
	}
	return r.fieldClientAuth
}

func (r *Readonly_TLSConfig) GetCipherSuites() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldCipherSuites
}

func (r *Readonly_TLSConfig) GetCipherSuitesTls13() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldCipherSuitesTls13
}

func (r *Readonly_TLSConfig) GetEnableAlpn() bool {
	if r == nil {
		var zero bool
		return zero
	}
	return r.fieldEnableAlpn
}

func (r *Readonly_TLSConfig) GetClientCertType() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldClientCertType
}

func (r *Readonly_TLSConfig) GetKeyType() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldKeyType
}

func (r *Readonly_TLSConfig) GetKeyPassword() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldKeyPassword
}

func (r *Readonly_TLSConfig) GetTlsAuthUsername() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldTlsAuthUsername
}

func (r *Readonly_TLSConfig) GetTlsAuthPassword() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldTlsAuthPassword
}

// ===== Clone methods for AuthConfig ===== Message ====
func (m *AuthConfig) Clone() *AuthConfig {
	if m == nil {
		return new(AuthConfig)
	}
	return proto.Clone(m).(*AuthConfig)
}

// ===== Merge methods for AuthConfig ===== Message ====
func (m *AuthConfig) Merge(src *AuthConfig) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for AuthConfig ===== Message ====
func (m *AuthConfig) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableTextIndent(m))
}

// ===== GetMessageReflectType methods for AuthConfig ===== Message =====
func (_ *AuthConfig) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[AuthConfig]()
}

// ===== Readonly wrapper for AuthConfig ===== Message ====
type Readonly_AuthConfig struct {
	protoData                 *AuthConfig
	fieldToken                string
	fieldTokenRefreshInterval *durationpb.Duration
	fieldUsername             string
	fieldPassword             string
}

func (r *Readonly_AuthConfig) ReadonlyProtoReflect() innerFile_atframe_etcd_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *AuthConfig) ToReadonly() *Readonly_AuthConfig {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_AuthConfig{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_AuthConfig) CloneMessage() *AuthConfig {
	if r == nil {
		return new(AuthConfig)
	}
	return r.protoData.Clone()
}

func (r *Readonly_AuthConfig) ToMessage() *AuthConfig {
	return r.CloneMessage()
}

func (r Readonly_AuthConfig) LogValue() slog.Value {
	return r.protoData.LogValue()
}

func (r *Readonly_AuthConfig) initFromProto(src *AuthConfig) {
	if r == nil || src == nil {
		return
	}
	r.fieldToken = src.GetToken()
	if v := src.GetTokenRefreshInterval(); v != nil {
		r.fieldTokenRefreshInterval = proto.Clone(v).(*durationpb.Duration)
	} else {
		r.fieldTokenRefreshInterval = nil
	}
	r.fieldUsername = src.GetUsername()
	r.fieldPassword = src.GetPassword()
}

func (r *Readonly_AuthConfig) GetToken() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldToken
}

func (r *Readonly_AuthConfig) GetTokenRefreshInterval() *durationpb.Duration {
	if r == nil {
		var zero *durationpb.Duration
		return zero
	}
	return r.fieldTokenRefreshInterval
}

func (r *Readonly_AuthConfig) GetUsername() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldUsername
}

func (r *Readonly_AuthConfig) GetPassword() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldPassword
}

// ===== Mutable methods for AuthConfig ===== Message =====
func (m *AuthConfig) MutableTokenRefreshInterval() *durationpb.Duration {
	if m.TokenRefreshInterval == nil {
		m.TokenRefreshInterval = new(durationpb.Duration)
	}
	return m.TokenRefreshInterval
}

// ===== Clone methods for EtcdClusterConf ===== Message ====
func (m *EtcdClusterConf) Clone() *EtcdClusterConf {
	if m == nil {
		return new(EtcdClusterConf)
	}
	return proto.Clone(m).(*EtcdClusterConf)
}

// ===== Merge methods for EtcdClusterConf ===== Message ====
func (m *EtcdClusterConf) Merge(src *EtcdClusterConf) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for EtcdClusterConf ===== Message ====
func (m *EtcdClusterConf) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableTextIndent(m))
}

// ===== GetMessageReflectType methods for EtcdClusterConf ===== Message =====
func (_ *EtcdClusterConf) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[EtcdClusterConf]()
}

// ===== Readonly wrapper for EtcdClusterConf ===== Message ====
type Readonly_EtcdClusterConf struct {
	protoData        *EtcdClusterConf
	fieldEndpoints   []string
	fieldDialTimeout *durationpb.Duration
	fieldTls         *Readonly_TLSConfig
	fieldAuth        *Readonly_AuthConfig
	fieldRetry       *Readonly_RetryConfig
	fieldDebugMode   bool
	fieldUserAgent   string
}

func (r *Readonly_EtcdClusterConf) ReadonlyProtoReflect() innerFile_atframe_etcd_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *EtcdClusterConf) ToReadonly() *Readonly_EtcdClusterConf {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_EtcdClusterConf{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_EtcdClusterConf) CloneMessage() *EtcdClusterConf {
	if r == nil {
		return new(EtcdClusterConf)
	}
	return r.protoData.Clone()
}

func (r *Readonly_EtcdClusterConf) ToMessage() *EtcdClusterConf {
	return r.CloneMessage()
}

func (r Readonly_EtcdClusterConf) LogValue() slog.Value {
	return r.protoData.LogValue()
}

func (r *Readonly_EtcdClusterConf) initFromProto(src *EtcdClusterConf) {
	if r == nil || src == nil {
		return
	}
	if v := src.GetEndpoints(); len(v) != 0 {
		copied := make([]string, len(v))
		copy(copied, v)
		r.fieldEndpoints = copied
	} else {
		r.fieldEndpoints = nil
	}
	if v := src.GetDialTimeout(); v != nil {
		r.fieldDialTimeout = proto.Clone(v).(*durationpb.Duration)
	} else {
		r.fieldDialTimeout = nil
	}
	if v := src.GetTls(); v != nil {
		r.fieldTls = v.ToReadonly()
	} else {
		r.fieldTls = nil
	}
	if v := src.GetAuth(); v != nil {
		r.fieldAuth = v.ToReadonly()
	} else {
		r.fieldAuth = nil
	}
	if v := src.GetRetry(); v != nil {
		r.fieldRetry = v.ToReadonly()
	} else {
		r.fieldRetry = nil
	}
	r.fieldDebugMode = src.GetDebugMode()
	r.fieldUserAgent = src.GetUserAgent()
}

func (r *Readonly_EtcdClusterConf) GetEndpoints() []string {
	if r == nil {
		var zero []string
		return zero
	}
	return r.fieldEndpoints
}

func (r *Readonly_EtcdClusterConf) GetDialTimeout() *durationpb.Duration {
	if r == nil {
		var zero *durationpb.Duration
		return zero
	}
	return r.fieldDialTimeout
}

func (r *Readonly_EtcdClusterConf) GetTls() *Readonly_TLSConfig {
	if r == nil {
		var zero *Readonly_TLSConfig
		return zero
	}
	return r.fieldTls
}

func (r *Readonly_EtcdClusterConf) GetAuth() *Readonly_AuthConfig {
	if r == nil {
		var zero *Readonly_AuthConfig
		return zero
	}
	return r.fieldAuth
}

func (r *Readonly_EtcdClusterConf) GetRetry() *Readonly_RetryConfig {
	if r == nil {
		var zero *Readonly_RetryConfig
		return zero
	}
	return r.fieldRetry
}

func (r *Readonly_EtcdClusterConf) GetDebugMode() bool {
	if r == nil {
		var zero bool
		return zero
	}
	return r.fieldDebugMode
}

func (r *Readonly_EtcdClusterConf) GetUserAgent() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldUserAgent
}

// ===== Mutable methods for EtcdClusterConf ===== Repeated =====
func (m *EtcdClusterConf) MutableEndpoints() []string {
	if m.Endpoints == nil {
		m.Endpoints = []string{}
	}
	return m.Endpoints
}

// ===== ReverseIfNil methods for EtcdClusterConf ===== Repeated =====
func (m *EtcdClusterConf) ReverseIfNilEndpoints(l int) []string {
	if m.Endpoints == nil {
		m.Endpoints = make([]string, 0, l)
	}
	return m.Endpoints
}

// ===== Append methods for EtcdClusterConf ===== Repeated =====
func (m *EtcdClusterConf) AppendEndpoints(d string) {
	if m.Endpoints == nil {
		m.Endpoints = []string{}
	}
	m.Endpoints = append(m.Endpoints, d)
}

// ===== Append methods for EtcdClusterConf ===== Repeated =====
func (m *EtcdClusterConf) AppendAndReverseEndpoints(l int, d string) {
	if m.Endpoints == nil {
		m.Endpoints = make([]string, 0, l)
	}
	m.Endpoints = append(m.Endpoints, d)
}

// ===== Merge methods for EtcdClusterConf ===== Repeated =====
func (m *EtcdClusterConf) MergeEndpoints(d []string) []string {
	if m.Endpoints == nil {
		m.Endpoints = []string{}
	}
	m.Endpoints = append(m.Endpoints, d...)
	return m.Endpoints
}

// ===== RemoveLast methods for EtcdClusterConf ===== Repeated =====
func (m *EtcdClusterConf) RemoveLastEndpoints() {
	if m.Endpoints == nil {
		m.Endpoints = []string{}
	}
	if len(m.Endpoints) != 0 {
		m.Endpoints = m.Endpoints[:len(m.Endpoints)-1]
	}
}

// ===== Mutable methods for EtcdClusterConf ===== Message =====
func (m *EtcdClusterConf) MutableDialTimeout() *durationpb.Duration {
	if m.DialTimeout == nil {
		m.DialTimeout = new(durationpb.Duration)
	}
	return m.DialTimeout
}

// ===== Mutable methods for EtcdClusterConf ===== Message =====
func (m *EtcdClusterConf) MutableTls() *TLSConfig {
	if m.Tls == nil {
		m.Tls = new(TLSConfig)
	}
	return m.Tls
}

// ===== Mutable methods for EtcdClusterConf ===== Message =====
func (m *EtcdClusterConf) MutableAuth() *AuthConfig {
	if m.Auth == nil {
		m.Auth = new(AuthConfig)
	}
	return m.Auth
}

// ===== Mutable methods for EtcdClusterConf ===== Message =====
func (m *EtcdClusterConf) MutableRetry() *RetryConfig {
	if m.Retry == nil {
		m.Retry = new(RetryConfig)
	}
	return m.Retry
}

// ===== Clone methods for EtcdResponseHeader ===== Message ====
func (m *EtcdResponseHeader) Clone() *EtcdResponseHeader {
	if m == nil {
		return new(EtcdResponseHeader)
	}
	return proto.Clone(m).(*EtcdResponseHeader)
}

// ===== Merge methods for EtcdResponseHeader ===== Message ====
func (m *EtcdResponseHeader) Merge(src *EtcdResponseHeader) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for EtcdResponseHeader ===== Message ====
func (m *EtcdResponseHeader) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableTextIndent(m))
}

// ===== GetMessageReflectType methods for EtcdResponseHeader ===== Message =====
func (_ *EtcdResponseHeader) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[EtcdResponseHeader]()
}

// ===== Readonly wrapper for EtcdResponseHeader ===== Message ====
type Readonly_EtcdResponseHeader struct {
	protoData      *EtcdResponseHeader
	fieldClusterId uint64
	fieldMemberId  uint64
	fieldRevision  int64
	fieldRaftTerm  uint64
}

func (r *Readonly_EtcdResponseHeader) ReadonlyProtoReflect() innerFile_atframe_etcd_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *EtcdResponseHeader) ToReadonly() *Readonly_EtcdResponseHeader {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_EtcdResponseHeader{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_EtcdResponseHeader) CloneMessage() *EtcdResponseHeader {
	if r == nil {
		return new(EtcdResponseHeader)
	}
	return r.protoData.Clone()
}

func (r *Readonly_EtcdResponseHeader) ToMessage() *EtcdResponseHeader {
	return r.CloneMessage()
}

func (r Readonly_EtcdResponseHeader) LogValue() slog.Value {
	return r.protoData.LogValue()
}

func (r *Readonly_EtcdResponseHeader) initFromProto(src *EtcdResponseHeader) {
	if r == nil || src == nil {
		return
	}
	r.fieldClusterId = src.GetClusterId()
	r.fieldMemberId = src.GetMemberId()
	r.fieldRevision = src.GetRevision()
	r.fieldRaftTerm = src.GetRaftTerm()
}

func (r *Readonly_EtcdResponseHeader) GetClusterId() uint64 {
	if r == nil {
		var zero uint64
		return zero
	}
	return r.fieldClusterId
}

func (r *Readonly_EtcdResponseHeader) GetMemberId() uint64 {
	if r == nil {
		var zero uint64
		return zero
	}
	return r.fieldMemberId
}

func (r *Readonly_EtcdResponseHeader) GetRevision() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.fieldRevision
}

func (r *Readonly_EtcdResponseHeader) GetRaftTerm() uint64 {
	if r == nil {
		var zero uint64
		return zero
	}
	return r.fieldRaftTerm
}

// ===== Clone methods for EtcdKeyValue ===== Message ====
func (m *EtcdKeyValue) Clone() *EtcdKeyValue {
	if m == nil {
		return new(EtcdKeyValue)
	}
	return proto.Clone(m).(*EtcdKeyValue)
}

// ===== Merge methods for EtcdKeyValue ===== Message ====
func (m *EtcdKeyValue) Merge(src *EtcdKeyValue) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for EtcdKeyValue ===== Message ====
func (m *EtcdKeyValue) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableTextIndent(m))
}

// ===== GetMessageReflectType methods for EtcdKeyValue ===== Message =====
func (_ *EtcdKeyValue) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[EtcdKeyValue]()
}

// ===== Readonly wrapper for EtcdKeyValue ===== Message ====
type Readonly_EtcdKeyValue struct {
	protoData           *EtcdKeyValue
	fieldKey            []byte
	fieldValue          []byte
	fieldCreateRevision int64
	fieldModRevision    int64
	fieldVersion        int64
	fieldLease          int64
}

func (r *Readonly_EtcdKeyValue) ReadonlyProtoReflect() innerFile_atframe_etcd_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *EtcdKeyValue) ToReadonly() *Readonly_EtcdKeyValue {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_EtcdKeyValue{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_EtcdKeyValue) CloneMessage() *EtcdKeyValue {
	if r == nil {
		return new(EtcdKeyValue)
	}
	return r.protoData.Clone()
}

func (r *Readonly_EtcdKeyValue) ToMessage() *EtcdKeyValue {
	return r.CloneMessage()
}

func (r Readonly_EtcdKeyValue) LogValue() slog.Value {
	return r.protoData.LogValue()
}

func (r *Readonly_EtcdKeyValue) initFromProto(src *EtcdKeyValue) {
	if r == nil || src == nil {
		return
	}
	if v := src.GetKey(); len(v) != 0 {
		r.fieldKey = append([]byte(nil), v...)
	} else {
		r.fieldKey = nil
	}
	if v := src.GetValue(); len(v) != 0 {
		r.fieldValue = append([]byte(nil), v...)
	} else {
		r.fieldValue = nil
	}
	r.fieldCreateRevision = src.GetCreateRevision()
	r.fieldModRevision = src.GetModRevision()
	r.fieldVersion = src.GetVersion()
	r.fieldLease = src.GetLease()
}

func (r *Readonly_EtcdKeyValue) GetKey() []byte {
	if r == nil {
		var zero []byte
		return zero
	}
	if len(r.fieldKey) == 0 {
		return r.fieldKey
	}
	dup := make([]byte, len(r.fieldKey))
	copy(dup, r.fieldKey)
	return dup
}

func (r *Readonly_EtcdKeyValue) GetValue() []byte {
	if r == nil {
		var zero []byte
		return zero
	}
	if len(r.fieldValue) == 0 {
		return r.fieldValue
	}
	dup := make([]byte, len(r.fieldValue))
	copy(dup, r.fieldValue)
	return dup
}

func (r *Readonly_EtcdKeyValue) GetCreateRevision() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.fieldCreateRevision
}

func (r *Readonly_EtcdKeyValue) GetModRevision() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.fieldModRevision
}

func (r *Readonly_EtcdKeyValue) GetVersion() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.fieldVersion
}

func (r *Readonly_EtcdKeyValue) GetLease() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.fieldLease
}

// ===== Clone methods for EtcdWatchEvent ===== Message ====
func (m *EtcdWatchEvent) Clone() *EtcdWatchEvent {
	if m == nil {
		return new(EtcdWatchEvent)
	}
	return proto.Clone(m).(*EtcdWatchEvent)
}

// ===== Merge methods for EtcdWatchEvent ===== Message ====
func (m *EtcdWatchEvent) Merge(src *EtcdWatchEvent) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for EtcdWatchEvent ===== Message ====
func (m *EtcdWatchEvent) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableTextIndent(m))
}

// ===== GetMessageReflectType methods for EtcdWatchEvent ===== Message =====
func (_ *EtcdWatchEvent) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[EtcdWatchEvent]()
}

// ===== Readonly wrapper for EtcdWatchEvent ===== Message ====
type Readonly_EtcdWatchEvent struct {
	protoData   *EtcdWatchEvent
	fieldType   EtcdWatchEventType
	fieldKv     *Readonly_EtcdKeyValue
	fieldPrevKv *Readonly_EtcdKeyValue
}

func (r *Readonly_EtcdWatchEvent) ReadonlyProtoReflect() innerFile_atframe_etcd_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *EtcdWatchEvent) ToReadonly() *Readonly_EtcdWatchEvent {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_EtcdWatchEvent{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_EtcdWatchEvent) CloneMessage() *EtcdWatchEvent {
	if r == nil {
		return new(EtcdWatchEvent)
	}
	return r.protoData.Clone()
}

func (r *Readonly_EtcdWatchEvent) ToMessage() *EtcdWatchEvent {
	return r.CloneMessage()
}

func (r Readonly_EtcdWatchEvent) LogValue() slog.Value {
	return r.protoData.LogValue()
}

func (r *Readonly_EtcdWatchEvent) initFromProto(src *EtcdWatchEvent) {
	if r == nil || src == nil {
		return
	}
	r.fieldType = src.GetType()
	if v := src.GetKv(); v != nil {
		r.fieldKv = v.ToReadonly()
	} else {
		r.fieldKv = nil
	}
	if v := src.GetPrevKv(); v != nil {
		r.fieldPrevKv = v.ToReadonly()
	} else {
		r.fieldPrevKv = nil
	}
}

func (r *Readonly_EtcdWatchEvent) GetType() EtcdWatchEventType {
	if r == nil {
		var zero EtcdWatchEventType
		return zero
	}
	return r.fieldType
}

func (r *Readonly_EtcdWatchEvent) GetKv() *Readonly_EtcdKeyValue {
	if r == nil {
		var zero *Readonly_EtcdKeyValue
		return zero
	}
	return r.fieldKv
}

func (r *Readonly_EtcdWatchEvent) GetPrevKv() *Readonly_EtcdKeyValue {
	if r == nil {
		var zero *Readonly_EtcdKeyValue
		return zero
	}
	return r.fieldPrevKv
}

// ===== Mutable methods for EtcdWatchEvent ===== Message =====
func (m *EtcdWatchEvent) MutableKv() *EtcdKeyValue {
	if m.Kv == nil {
		m.Kv = new(EtcdKeyValue)
	}
	return m.Kv
}

// ===== Mutable methods for EtcdWatchEvent ===== Message =====
func (m *EtcdWatchEvent) MutablePrevKv() *EtcdKeyValue {
	if m.PrevKv == nil {
		m.PrevKv = new(EtcdKeyValue)
	}
	return m.PrevKv
}

// ===== Clone methods for EtcdArea ===== Message ====
func (m *EtcdArea) Clone() *EtcdArea {
	if m == nil {
		return new(EtcdArea)
	}
	return proto.Clone(m).(*EtcdArea)
}

// ===== Merge methods for EtcdArea ===== Message ====
func (m *EtcdArea) Merge(src *EtcdArea) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for EtcdArea ===== Message ====
func (m *EtcdArea) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableTextIndent(m))
}

// ===== GetMessageReflectType methods for EtcdArea ===== Message =====
func (_ *EtcdArea) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[EtcdArea]()
}

// ===== Readonly wrapper for EtcdArea ===== Message ====
type Readonly_EtcdArea struct {
	protoData     *EtcdArea
	fieldRegion   string
	fieldDistrict string
	fieldZoneId   uint32
}

func (r *Readonly_EtcdArea) ReadonlyProtoReflect() innerFile_atframe_etcd_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *EtcdArea) ToReadonly() *Readonly_EtcdArea {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_EtcdArea{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_EtcdArea) CloneMessage() *EtcdArea {
	if r == nil {
		return new(EtcdArea)
	}
	return r.protoData.Clone()
}

func (r *Readonly_EtcdArea) ToMessage() *EtcdArea {
	return r.CloneMessage()
}

func (r Readonly_EtcdArea) LogValue() slog.Value {
	return r.protoData.LogValue()
}

func (r *Readonly_EtcdArea) initFromProto(src *EtcdArea) {
	if r == nil || src == nil {
		return
	}
	r.fieldRegion = src.GetRegion()
	r.fieldDistrict = src.GetDistrict()
	r.fieldZoneId = src.GetZoneId()
}

func (r *Readonly_EtcdArea) GetRegion() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldRegion
}

func (r *Readonly_EtcdArea) GetDistrict() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldDistrict
}

func (r *Readonly_EtcdArea) GetZoneId() uint32 {
	if r == nil {
		var zero uint32
		return zero
	}
	return r.fieldZoneId
}

// ===== Clone methods for EtcdMetadata ===== Message ====
func (m *EtcdMetadata) Clone() *EtcdMetadata {
	if m == nil {
		return new(EtcdMetadata)
	}
	return proto.Clone(m).(*EtcdMetadata)
}

// ===== Merge methods for EtcdMetadata ===== Message ====
func (m *EtcdMetadata) Merge(src *EtcdMetadata) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for EtcdMetadata ===== Message ====
func (m *EtcdMetadata) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableTextIndent(m))
}

// ===== GetMessageReflectType methods for EtcdMetadata ===== Message =====
func (_ *EtcdMetadata) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[EtcdMetadata]()
}

// ===== Readonly wrapper for EtcdMetadata ===== Message ====
type Readonly_EtcdMetadata struct {
	protoData          *EtcdMetadata
	fieldApiVersion    string
	fieldKind          string
	fieldGroup         string
	fieldName          string
	fieldNamespaceName string
	fieldUid           string
	fieldServiceSubset string
	fieldLabels        map[string]string
}

func (r *Readonly_EtcdMetadata) ReadonlyProtoReflect() innerFile_atframe_etcd_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *EtcdMetadata) ToReadonly() *Readonly_EtcdMetadata {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_EtcdMetadata{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_EtcdMetadata) CloneMessage() *EtcdMetadata {
	if r == nil {
		return new(EtcdMetadata)
	}
	return r.protoData.Clone()
}

func (r *Readonly_EtcdMetadata) ToMessage() *EtcdMetadata {
	return r.CloneMessage()
}

func (r Readonly_EtcdMetadata) LogValue() slog.Value {
	return r.protoData.LogValue()
}

func (r *Readonly_EtcdMetadata) initFromProto(src *EtcdMetadata) {
	if r == nil || src == nil {
		return
	}
	r.fieldApiVersion = src.GetApiVersion()
	r.fieldKind = src.GetKind()
	r.fieldGroup = src.GetGroup()
	r.fieldName = src.GetName()
	r.fieldNamespaceName = src.GetNamespaceName()
	r.fieldUid = src.GetUid()
	r.fieldServiceSubset = src.GetServiceSubset()
	if v := src.GetLabels(); len(v) != 0 {
		copied := make(map[string]string, len(v))
		for mk, mv := range v {
			copied[mk] = mv
		}
		r.fieldLabels = copied
	} else {
		r.fieldLabels = nil
	}
}

func (r *Readonly_EtcdMetadata) GetApiVersion() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldApiVersion
}

func (r *Readonly_EtcdMetadata) GetKind() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldKind
}

func (r *Readonly_EtcdMetadata) GetGroup() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldGroup
}

func (r *Readonly_EtcdMetadata) GetName() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldName
}

func (r *Readonly_EtcdMetadata) GetNamespaceName() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldNamespaceName
}

func (r *Readonly_EtcdMetadata) GetUid() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldUid
}

func (r *Readonly_EtcdMetadata) GetServiceSubset() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldServiceSubset
}

func (r *Readonly_EtcdMetadata) GetLabels() map[string]string {
	if r == nil {
		var zero map[string]string
		return zero
	}
	return r.fieldLabels
}

// ===== Mutable methods for EtcdMetadata ===== Map =====
func (m *EtcdMetadata) MutableLabels() map[string]string {
	if m.Labels == nil {
		m.Labels = make(map[string]string, 0)
	}
	return m.Labels
}

// ===== Clone methods for EtcdGateway ===== Message ====
func (m *EtcdGateway) Clone() *EtcdGateway {
	if m == nil {
		return new(EtcdGateway)
	}
	return proto.Clone(m).(*EtcdGateway)
}

// ===== Merge methods for EtcdGateway ===== Message ====
func (m *EtcdGateway) Merge(src *EtcdGateway) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for EtcdGateway ===== Message ====
func (m *EtcdGateway) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableTextIndent(m))
}

// ===== GetMessageReflectType methods for EtcdGateway ===== Message =====
func (_ *EtcdGateway) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[EtcdGateway]()
}

// ===== Readonly wrapper for EtcdGateway ===== Message ====
type Readonly_EtcdGateway struct {
	protoData            *EtcdGateway
	fieldAddress         string
	fieldMatchHosts      []string
	fieldMatchNamespaces []string
	fieldMatchLabels     map[string]string
}

func (r *Readonly_EtcdGateway) ReadonlyProtoReflect() innerFile_atframe_etcd_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *EtcdGateway) ToReadonly() *Readonly_EtcdGateway {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_EtcdGateway{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_EtcdGateway) CloneMessage() *EtcdGateway {
	if r == nil {
		return new(EtcdGateway)
	}
	return r.protoData.Clone()
}

func (r *Readonly_EtcdGateway) ToMessage() *EtcdGateway {
	return r.CloneMessage()
}

func (r Readonly_EtcdGateway) LogValue() slog.Value {
	return r.protoData.LogValue()
}

func (r *Readonly_EtcdGateway) initFromProto(src *EtcdGateway) {
	if r == nil || src == nil {
		return
	}
	r.fieldAddress = src.GetAddress()
	if v := src.GetMatchHosts(); len(v) != 0 {
		copied := make([]string, len(v))
		copy(copied, v)
		r.fieldMatchHosts = copied
	} else {
		r.fieldMatchHosts = nil
	}
	if v := src.GetMatchNamespaces(); len(v) != 0 {
		copied := make([]string, len(v))
		copy(copied, v)
		r.fieldMatchNamespaces = copied
	} else {
		r.fieldMatchNamespaces = nil
	}
	if v := src.GetMatchLabels(); len(v) != 0 {
		copied := make(map[string]string, len(v))
		for mk, mv := range v {
			copied[mk] = mv
		}
		r.fieldMatchLabels = copied
	} else {
		r.fieldMatchLabels = nil
	}
}

func (r *Readonly_EtcdGateway) GetAddress() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldAddress
}

func (r *Readonly_EtcdGateway) GetMatchHosts() []string {
	if r == nil {
		var zero []string
		return zero
	}
	return r.fieldMatchHosts
}

func (r *Readonly_EtcdGateway) GetMatchNamespaces() []string {
	if r == nil {
		var zero []string
		return zero
	}
	return r.fieldMatchNamespaces
}

func (r *Readonly_EtcdGateway) GetMatchLabels() map[string]string {
	if r == nil {
		var zero map[string]string
		return zero
	}
	return r.fieldMatchLabels
}

// ===== Mutable methods for EtcdGateway ===== Repeated =====
func (m *EtcdGateway) MutableMatchHosts() []string {
	if m.MatchHosts == nil {
		m.MatchHosts = []string{}
	}
	return m.MatchHosts
}

// ===== ReverseIfNil methods for EtcdGateway ===== Repeated =====
func (m *EtcdGateway) ReverseIfNilMatchHosts(l int) []string {
	if m.MatchHosts == nil {
		m.MatchHosts = make([]string, 0, l)
	}
	return m.MatchHosts
}

// ===== Append methods for EtcdGateway ===== Repeated =====
func (m *EtcdGateway) AppendMatchHosts(d string) {
	if m.MatchHosts == nil {
		m.MatchHosts = []string{}
	}
	m.MatchHosts = append(m.MatchHosts, d)
}

// ===== Append methods for EtcdGateway ===== Repeated =====
func (m *EtcdGateway) AppendAndReverseMatchHosts(l int, d string) {
	if m.MatchHosts == nil {
		m.MatchHosts = make([]string, 0, l)
	}
	m.MatchHosts = append(m.MatchHosts, d)
}

// ===== Merge methods for EtcdGateway ===== Repeated =====
func (m *EtcdGateway) MergeMatchHosts(d []string) []string {
	if m.MatchHosts == nil {
		m.MatchHosts = []string{}
	}
	m.MatchHosts = append(m.MatchHosts, d...)
	return m.MatchHosts
}

// ===== RemoveLast methods for EtcdGateway ===== Repeated =====
func (m *EtcdGateway) RemoveLastMatchHosts() {
	if m.MatchHosts == nil {
		m.MatchHosts = []string{}
	}
	if len(m.MatchHosts) != 0 {
		m.MatchHosts = m.MatchHosts[:len(m.MatchHosts)-1]
	}
}

// ===== Mutable methods for EtcdGateway ===== Repeated =====
func (m *EtcdGateway) MutableMatchNamespaces() []string {
	if m.MatchNamespaces == nil {
		m.MatchNamespaces = []string{}
	}
	return m.MatchNamespaces
}

// ===== ReverseIfNil methods for EtcdGateway ===== Repeated =====
func (m *EtcdGateway) ReverseIfNilMatchNamespaces(l int) []string {
	if m.MatchNamespaces == nil {
		m.MatchNamespaces = make([]string, 0, l)
	}
	return m.MatchNamespaces
}

// ===== Append methods for EtcdGateway ===== Repeated =====
func (m *EtcdGateway) AppendMatchNamespaces(d string) {
	if m.MatchNamespaces == nil {
		m.MatchNamespaces = []string{}
	}
	m.MatchNamespaces = append(m.MatchNamespaces, d)
}

// ===== Append methods for EtcdGateway ===== Repeated =====
func (m *EtcdGateway) AppendAndReverseMatchNamespaces(l int, d string) {
	if m.MatchNamespaces == nil {
		m.MatchNamespaces = make([]string, 0, l)
	}
	m.MatchNamespaces = append(m.MatchNamespaces, d)
}

// ===== Merge methods for EtcdGateway ===== Repeated =====
func (m *EtcdGateway) MergeMatchNamespaces(d []string) []string {
	if m.MatchNamespaces == nil {
		m.MatchNamespaces = []string{}
	}
	m.MatchNamespaces = append(m.MatchNamespaces, d...)
	return m.MatchNamespaces
}

// ===== RemoveLast methods for EtcdGateway ===== Repeated =====
func (m *EtcdGateway) RemoveLastMatchNamespaces() {
	if m.MatchNamespaces == nil {
		m.MatchNamespaces = []string{}
	}
	if len(m.MatchNamespaces) != 0 {
		m.MatchNamespaces = m.MatchNamespaces[:len(m.MatchNamespaces)-1]
	}
}

// ===== Mutable methods for EtcdGateway ===== Map =====
func (m *EtcdGateway) MutableMatchLabels() map[string]string {
	if m.MatchLabels == nil {
		m.MatchLabels = make(map[string]string, 0)
	}
	return m.MatchLabels
}

// ===== Clone methods for EtcdDiscoveryNode ===== Message ====
func (m *EtcdDiscoveryNode) Clone() *EtcdDiscoveryNode {
	if m == nil {
		return new(EtcdDiscoveryNode)
	}
	return proto.Clone(m).(*EtcdDiscoveryNode)
}

// ===== Merge methods for EtcdDiscoveryNode ===== Message ====
func (m *EtcdDiscoveryNode) Merge(src *EtcdDiscoveryNode) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for EtcdDiscoveryNode ===== Message ====
func (m *EtcdDiscoveryNode) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableTextIndent(m))
}

// ===== GetMessageReflectType methods for EtcdDiscoveryNode ===== Message =====
func (_ *EtcdDiscoveryNode) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[EtcdDiscoveryNode]()
}

// ===== Readonly wrapper for EtcdDiscoveryNode ===== Message ====
type Readonly_EtcdDiscoveryNode struct {
	protoData           *EtcdDiscoveryNode
	fieldId             uint64
	fieldName           string
	fieldHostname       string
	fieldPid            int32
	fieldListen         []string
	fieldHashCode       string
	fieldTypeId         uint64
	fieldTypeName       string
	fieldArea           *Readonly_EtcdArea
	fieldVersion        string
	fieldCustomData     string
	fieldIdentity       string
	fieldGateways       []*Readonly_EtcdGateway
	fieldMetadata       *Readonly_EtcdMetadata
	fieldCreateRevision uint64
	fieldModRevision    uint64
	fieldVersionNum     uint64
}

func (r *Readonly_EtcdDiscoveryNode) ReadonlyProtoReflect() innerFile_atframe_etcd_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *EtcdDiscoveryNode) ToReadonly() *Readonly_EtcdDiscoveryNode {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_EtcdDiscoveryNode{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_EtcdDiscoveryNode) CloneMessage() *EtcdDiscoveryNode {
	if r == nil {
		return new(EtcdDiscoveryNode)
	}
	return r.protoData.Clone()
}

func (r *Readonly_EtcdDiscoveryNode) ToMessage() *EtcdDiscoveryNode {
	return r.CloneMessage()
}

func (r Readonly_EtcdDiscoveryNode) LogValue() slog.Value {
	return r.protoData.LogValue()
}

func (r *Readonly_EtcdDiscoveryNode) initFromProto(src *EtcdDiscoveryNode) {
	if r == nil || src == nil {
		return
	}
	r.fieldId = src.GetId()
	r.fieldName = src.GetName()
	r.fieldHostname = src.GetHostname()
	r.fieldPid = src.GetPid()
	if v := src.GetListen(); len(v) != 0 {
		copied := make([]string, len(v))
		copy(copied, v)
		r.fieldListen = copied
	} else {
		r.fieldListen = nil
	}
	r.fieldHashCode = src.GetHashCode()
	r.fieldTypeId = src.GetTypeId()
	r.fieldTypeName = src.GetTypeName()
	if v := src.GetArea(); v != nil {
		r.fieldArea = v.ToReadonly()
	} else {
		r.fieldArea = nil
	}
	r.fieldVersion = src.GetVersion()
	r.fieldCustomData = src.GetCustomData()
	r.fieldIdentity = src.GetIdentity()
	if v := src.GetGateways(); len(v) != 0 {
		out := make([]*Readonly_EtcdGateway, 0, len(v))
		for _, item := range v {
			if item == nil {
				out = append(out, nil)
				continue
			}
			out = append(out, item.ToReadonly())
		}
		r.fieldGateways = out
	} else {
		r.fieldGateways = nil
	}
	if v := src.GetMetadata(); v != nil {
		r.fieldMetadata = v.ToReadonly()
	} else {
		r.fieldMetadata = nil
	}
	r.fieldCreateRevision = src.GetCreateRevision()
	r.fieldModRevision = src.GetModRevision()
	r.fieldVersionNum = src.GetVersionNum()
}

func (r *Readonly_EtcdDiscoveryNode) GetId() uint64 {
	if r == nil {
		var zero uint64
		return zero
	}
	return r.fieldId
}

func (r *Readonly_EtcdDiscoveryNode) GetName() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldName
}

func (r *Readonly_EtcdDiscoveryNode) GetHostname() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldHostname
}

func (r *Readonly_EtcdDiscoveryNode) GetPid() int32 {
	if r == nil {
		var zero int32
		return zero
	}
	return r.fieldPid
}

func (r *Readonly_EtcdDiscoveryNode) GetListen() []string {
	if r == nil {
		var zero []string
		return zero
	}
	return r.fieldListen
}

func (r *Readonly_EtcdDiscoveryNode) GetHashCode() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldHashCode
}

func (r *Readonly_EtcdDiscoveryNode) GetTypeId() uint64 {
	if r == nil {
		var zero uint64
		return zero
	}
	return r.fieldTypeId
}

func (r *Readonly_EtcdDiscoveryNode) GetTypeName() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldTypeName
}

func (r *Readonly_EtcdDiscoveryNode) GetArea() *Readonly_EtcdArea {
	if r == nil {
		var zero *Readonly_EtcdArea
		return zero
	}
	return r.fieldArea
}

func (r *Readonly_EtcdDiscoveryNode) GetVersion() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldVersion
}

func (r *Readonly_EtcdDiscoveryNode) GetCustomData() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldCustomData
}

func (r *Readonly_EtcdDiscoveryNode) GetIdentity() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldIdentity
}

func (r *Readonly_EtcdDiscoveryNode) GetGateways() []*Readonly_EtcdGateway {
	if r == nil {
		var zero []*Readonly_EtcdGateway
		return zero
	}
	return r.fieldGateways
}

func (r *Readonly_EtcdDiscoveryNode) GetMetadata() *Readonly_EtcdMetadata {
	if r == nil {
		var zero *Readonly_EtcdMetadata
		return zero
	}
	return r.fieldMetadata
}

func (r *Readonly_EtcdDiscoveryNode) GetCreateRevision() uint64 {
	if r == nil {
		var zero uint64
		return zero
	}
	return r.fieldCreateRevision
}

func (r *Readonly_EtcdDiscoveryNode) GetModRevision() uint64 {
	if r == nil {
		var zero uint64
		return zero
	}
	return r.fieldModRevision
}

func (r *Readonly_EtcdDiscoveryNode) GetVersionNum() uint64 {
	if r == nil {
		var zero uint64
		return zero
	}
	return r.fieldVersionNum
}

// ===== Mutable methods for EtcdDiscoveryNode ===== Repeated =====
func (m *EtcdDiscoveryNode) MutableListen() []string {
	if m.Listen == nil {
		m.Listen = []string{}
	}
	return m.Listen
}

// ===== ReverseIfNil methods for EtcdDiscoveryNode ===== Repeated =====
func (m *EtcdDiscoveryNode) ReverseIfNilListen(l int) []string {
	if m.Listen == nil {
		m.Listen = make([]string, 0, l)
	}
	return m.Listen
}

// ===== Append methods for EtcdDiscoveryNode ===== Repeated =====
func (m *EtcdDiscoveryNode) AppendListen(d string) {
	if m.Listen == nil {
		m.Listen = []string{}
	}
	m.Listen = append(m.Listen, d)
}

// ===== Append methods for EtcdDiscoveryNode ===== Repeated =====
func (m *EtcdDiscoveryNode) AppendAndReverseListen(l int, d string) {
	if m.Listen == nil {
		m.Listen = make([]string, 0, l)
	}
	m.Listen = append(m.Listen, d)
}

// ===== Merge methods for EtcdDiscoveryNode ===== Repeated =====
func (m *EtcdDiscoveryNode) MergeListen(d []string) []string {
	if m.Listen == nil {
		m.Listen = []string{}
	}
	m.Listen = append(m.Listen, d...)
	return m.Listen
}

// ===== RemoveLast methods for EtcdDiscoveryNode ===== Repeated =====
func (m *EtcdDiscoveryNode) RemoveLastListen() {
	if m.Listen == nil {
		m.Listen = []string{}
	}
	if len(m.Listen) != 0 {
		m.Listen = m.Listen[:len(m.Listen)-1]
	}
}

// ===== Mutable methods for EtcdDiscoveryNode ===== Message =====
func (m *EtcdDiscoveryNode) MutableArea() *EtcdArea {
	if m.Area == nil {
		m.Area = new(EtcdArea)
	}
	return m.Area
}

// ===== Mutable methods for EtcdDiscoveryNode ===== Repeated =====
func (m *EtcdDiscoveryNode) MutableGateways() []*EtcdGateway {
	if m.Gateways == nil {
		m.Gateways = []*EtcdGateway{}
	}
	return m.Gateways
}

// ===== ReverseIfNil methods for EtcdDiscoveryNode ===== Repeated =====
func (m *EtcdDiscoveryNode) ReverseIfNilGateways(l int) []*EtcdGateway {
	if m.Gateways == nil {
		m.Gateways = make([]*EtcdGateway, 0, l)
	}
	return m.Gateways
}

// ===== Append methods for EtcdDiscoveryNode ===== Repeated =====
func (m *EtcdDiscoveryNode) AppendGateways(d *EtcdGateway) {
	if m.Gateways == nil {
		m.Gateways = []*EtcdGateway{}
	}
	m.Gateways = append(m.Gateways, d)
}

// ===== Append methods for EtcdDiscoveryNode ===== Repeated =====
func (m *EtcdDiscoveryNode) AppendAndReverseGateways(l int, d *EtcdGateway) {
	if m.Gateways == nil {
		m.Gateways = make([]*EtcdGateway, 0, l)
	}
	m.Gateways = append(m.Gateways, d)
}

// ===== Add methods for EtcdDiscoveryNode ===== Repeated =====
func (m *EtcdDiscoveryNode) AddGateways() *EtcdGateway {
	if m.Gateways == nil {
		m.Gateways = []*EtcdGateway{}
	}
	addValue := new(EtcdGateway)
	m.Gateways = append(m.Gateways, addValue)
	return addValue
}

// ===== Merge methods for EtcdDiscoveryNode ===== Repeated =====
func (m *EtcdDiscoveryNode) MergeGateways(d []*EtcdGateway) []*EtcdGateway {
	if m.Gateways == nil {
		m.Gateways = []*EtcdGateway{}
	}
	m.Gateways = append(m.Gateways, d...)
	return m.Gateways
}

// ===== RemoveLast methods for EtcdDiscoveryNode ===== Repeated =====
func (m *EtcdDiscoveryNode) RemoveLastGateways() {
	if m.Gateways == nil {
		m.Gateways = []*EtcdGateway{}
	}
	if len(m.Gateways) != 0 {
		m.Gateways = m.Gateways[:len(m.Gateways)-1]
	}
}

// ===== Mutable methods for EtcdDiscoveryNode ===== Message =====
func (m *EtcdDiscoveryNode) MutableMetadata() *EtcdMetadata {
	if m.Metadata == nil {
		m.Metadata = new(EtcdMetadata)
	}
	return m.Metadata
}
