// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: atframe/etcd.proto

package atframe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BackoffType defines the retry backoff strategy
type BackoffType int32

const (
	BackoffType_BACKOFF_TYPE_UNSPECIFIED BackoffType = 0
	BackoffType_BACKOFF_FIXED            BackoffType = 1
	BackoffType_BACKOFF_LINEAR           BackoffType = 2
	BackoffType_BACKOFF_EXPONENTIAL      BackoffType = 3
)

// Enum value maps for BackoffType.
var (
	BackoffType_name = map[int32]string{
		0: "BACKOFF_TYPE_UNSPECIFIED",
		1: "BACKOFF_FIXED",
		2: "BACKOFF_LINEAR",
		3: "BACKOFF_EXPONENTIAL",
	}
	BackoffType_value = map[string]int32{
		"BACKOFF_TYPE_UNSPECIFIED": 0,
		"BACKOFF_FIXED":            1,
		"BACKOFF_LINEAR":           2,
		"BACKOFF_EXPONENTIAL":      3,
	}
)

func (x BackoffType) Enum() *BackoffType {
	p := new(BackoffType)
	*p = x
	return p
}

func (x BackoffType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackoffType) Descriptor() protoreflect.EnumDescriptor {
	return file_atframe_etcd_proto_enumTypes[0].Descriptor()
}

func (BackoffType) Type() protoreflect.EnumType {
	return &file_atframe_etcd_proto_enumTypes[0]
}

func (x BackoffType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackoffType.Descriptor instead.
func (BackoffType) EnumDescriptor() ([]byte, []int) {
	return file_atframe_etcd_proto_rawDescGZIP(), []int{0}
}

// EtcdWatchEventType defines the type of watch event
type EtcdWatchEventType int32

const (
	EtcdWatchEventType_ETCD_WATCH_EVENT_TYPE_UNSPECIFIED EtcdWatchEventType = 0
	EtcdWatchEventType_ETCD_WATCH_EVENT_PUT              EtcdWatchEventType = 1
	EtcdWatchEventType_ETCD_WATCH_EVENT_DELETE           EtcdWatchEventType = 2
)

// Enum value maps for EtcdWatchEventType.
var (
	EtcdWatchEventType_name = map[int32]string{
		0: "ETCD_WATCH_EVENT_TYPE_UNSPECIFIED",
		1: "ETCD_WATCH_EVENT_PUT",
		2: "ETCD_WATCH_EVENT_DELETE",
	}
	EtcdWatchEventType_value = map[string]int32{
		"ETCD_WATCH_EVENT_TYPE_UNSPECIFIED": 0,
		"ETCD_WATCH_EVENT_PUT":              1,
		"ETCD_WATCH_EVENT_DELETE":           2,
	}
)

func (x EtcdWatchEventType) Enum() *EtcdWatchEventType {
	p := new(EtcdWatchEventType)
	*p = x
	return p
}

func (x EtcdWatchEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EtcdWatchEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_atframe_etcd_proto_enumTypes[1].Descriptor()
}

func (EtcdWatchEventType) Type() protoreflect.EnumType {
	return &file_atframe_etcd_proto_enumTypes[1]
}

func (x EtcdWatchEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EtcdWatchEventType.Descriptor instead.
func (EtcdWatchEventType) EnumDescriptor() ([]byte, []int) {
	return file_atframe_etcd_proto_rawDescGZIP(), []int{1}
}

// EtcdSearchMode defines search strategy for consistent hash
type EtcdSearchMode int32

const (
	EtcdSearchMode_ETCD_SEARCH_MODE_ALL                      EtcdSearchMode = 0
	EtcdSearchMode_ETCD_SEARCH_MODE_COMPACT                  EtcdSearchMode = 1
	EtcdSearchMode_ETCD_SEARCH_MODE_UNIQUE_NODE              EtcdSearchMode = 2
	EtcdSearchMode_ETCD_SEARCH_MODE_COMPACT_UNIQUE_NODE      EtcdSearchMode = 3
	EtcdSearchMode_ETCD_SEARCH_MODE_NEXT_NODE                EtcdSearchMode = 4
	EtcdSearchMode_ETCD_SEARCH_MODE_NEXT_COMPACT             EtcdSearchMode = 5
	EtcdSearchMode_ETCD_SEARCH_MODE_NEXT_UNIQUE_NODE         EtcdSearchMode = 6
	EtcdSearchMode_ETCD_SEARCH_MODE_NEXT_COMPACT_UNIQUE_NODE EtcdSearchMode = 7
)

// Enum value maps for EtcdSearchMode.
var (
	EtcdSearchMode_name = map[int32]string{
		0: "ETCD_SEARCH_MODE_ALL",
		1: "ETCD_SEARCH_MODE_COMPACT",
		2: "ETCD_SEARCH_MODE_UNIQUE_NODE",
		3: "ETCD_SEARCH_MODE_COMPACT_UNIQUE_NODE",
		4: "ETCD_SEARCH_MODE_NEXT_NODE",
		5: "ETCD_SEARCH_MODE_NEXT_COMPACT",
		6: "ETCD_SEARCH_MODE_NEXT_UNIQUE_NODE",
		7: "ETCD_SEARCH_MODE_NEXT_COMPACT_UNIQUE_NODE",
	}
	EtcdSearchMode_value = map[string]int32{
		"ETCD_SEARCH_MODE_ALL":                      0,
		"ETCD_SEARCH_MODE_COMPACT":                  1,
		"ETCD_SEARCH_MODE_UNIQUE_NODE":              2,
		"ETCD_SEARCH_MODE_COMPACT_UNIQUE_NODE":      3,
		"ETCD_SEARCH_MODE_NEXT_NODE":                4,
		"ETCD_SEARCH_MODE_NEXT_COMPACT":             5,
		"ETCD_SEARCH_MODE_NEXT_UNIQUE_NODE":         6,
		"ETCD_SEARCH_MODE_NEXT_COMPACT_UNIQUE_NODE": 7,
	}
)

func (x EtcdSearchMode) Enum() *EtcdSearchMode {
	p := new(EtcdSearchMode)
	*p = x
	return p
}

func (x EtcdSearchMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EtcdSearchMode) Descriptor() protoreflect.EnumDescriptor {
	return file_atframe_etcd_proto_enumTypes[2].Descriptor()
}

func (EtcdSearchMode) Type() protoreflect.EnumType {
	return &file_atframe_etcd_proto_enumTypes[2]
}

func (x EtcdSearchMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EtcdSearchMode.Descriptor instead.
func (EtcdSearchMode) EnumDescriptor() ([]byte, []int) {
	return file_atframe_etcd_proto_rawDescGZIP(), []int{2}
}

// RetryConfig defines retry policy for failed operations
type RetryConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MaxRetries      int32                  `protobuf:"varint,1,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`               // Maximum number of retries (default 3)
	InitialInterval *durationpb.Duration   `protobuf:"bytes,2,opt,name=initial_interval,json=initialInterval,proto3" json:"initial_interval,omitempty"` // Initial retry interval (default 1s)
	MaxInterval     *durationpb.Duration   `protobuf:"bytes,3,opt,name=max_interval,json=maxInterval,proto3" json:"max_interval,omitempty"`             // Maximum retry interval (default 30s)
	Backoff         BackoffType            `protobuf:"varint,4,opt,name=backoff,proto3,enum=atframework.etcd.BackoffType" json:"backoff,omitempty"`     // Backoff strategy (default EXPONENTIAL)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RetryConfig) Reset() {
	*x = RetryConfig{}
	mi := &file_atframe_etcd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryConfig) ProtoMessage() {}

func (x *RetryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_atframe_etcd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryConfig.ProtoReflect.Descriptor instead.
func (*RetryConfig) Descriptor() ([]byte, []int) {
	return file_atframe_etcd_proto_rawDescGZIP(), []int{0}
}

func (x *RetryConfig) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *RetryConfig) GetInitialInterval() *durationpb.Duration {
	if x != nil {
		return x.InitialInterval
	}
	return nil
}

func (x *RetryConfig) GetMaxInterval() *durationpb.Duration {
	if x != nil {
		return x.MaxInterval
	}
	return nil
}

func (x *RetryConfig) GetBackoff() BackoffType {
	if x != nil {
		return x.Backoff
	}
	return BackoffType_BACKOFF_TYPE_UNSPECIFIED
}

// TLSConfig defines TLS/SSL configuration for secure connections
type TLSConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Enabled            bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`                                                   // Enable TLS
	CertFile           string                 `protobuf:"bytes,2,opt,name=cert_file,json=certFile,proto3" json:"cert_file,omitempty"`                                  // Client certificate file path
	KeyFile            string                 `protobuf:"bytes,3,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`                                     // Client private key file path
	CaFile             string                 `protobuf:"bytes,4,opt,name=ca_file,json=caFile,proto3" json:"ca_file,omitempty"`                                        // CA certificate file path
	ServerName         string                 `protobuf:"bytes,5,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`                            // Server name for SNI
	InsecureSkipVerify bool                   `protobuf:"varint,6,opt,name=insecure_skip_verify,json=insecureSkipVerify,proto3" json:"insecure_skip_verify,omitempty"` // Skip certificate verification (insecure!)
	MinVersion         uint32                 `protobuf:"varint,7,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"`                           // Minimum TLS version (12=TLS1.2, 13=TLS1.3)
	MaxVersion         uint32                 `protobuf:"varint,8,opt,name=max_version,json=maxVersion,proto3" json:"max_version,omitempty"`                           // Maximum TLS version
	ClientAuth         int32                  `protobuf:"varint,9,opt,name=client_auth,json=clientAuth,proto3" json:"client_auth,omitempty"`                           // Client authentication type (tls.ClientAuthType)
	// Advanced TLS options
	CipherSuites      string `protobuf:"bytes,10,opt,name=cipher_suites,json=cipherSuites,proto3" json:"cipher_suites,omitempty"`                  // TLS cipher suites (comma-separated)
	CipherSuitesTls13 string `protobuf:"bytes,11,opt,name=cipher_suites_tls13,json=cipherSuitesTls13,proto3" json:"cipher_suites_tls13,omitempty"` // TLS 1.3 cipher suites (comma-separated)
	EnableAlpn        bool   `protobuf:"varint,12,opt,name=enable_alpn,json=enableAlpn,proto3" json:"enable_alpn,omitempty"`                       // Enable ALPN protocol negotiation
	ClientCertType    string `protobuf:"bytes,13,opt,name=client_cert_type,json=clientCertType,proto3" json:"client_cert_type,omitempty"`          // Certificate type: PEM, DER
	KeyType           string `protobuf:"bytes,14,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`                                 // Key type: PEM, DER, ENG
	KeyPassword       string `protobuf:"bytes,15,opt,name=key_password,json=keyPassword,proto3" json:"key_password,omitempty"`                     // Password for encrypted key files
	// mTLS authentication
	TlsAuthUsername string `protobuf:"bytes,16,opt,name=tls_auth_username,json=tlsAuthUsername,proto3" json:"tls_auth_username,omitempty"` // TLS auth username for client certificates
	TlsAuthPassword string `protobuf:"bytes,17,opt,name=tls_auth_password,json=tlsAuthPassword,proto3" json:"tls_auth_password,omitempty"` // TLS auth password for client certificates
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TLSConfig) Reset() {
	*x = TLSConfig{}
	mi := &file_atframe_etcd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSConfig) ProtoMessage() {}

func (x *TLSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_atframe_etcd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSConfig.ProtoReflect.Descriptor instead.
func (*TLSConfig) Descriptor() ([]byte, []int) {
	return file_atframe_etcd_proto_rawDescGZIP(), []int{1}
}

func (x *TLSConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *TLSConfig) GetCertFile() string {
	if x != nil {
		return x.CertFile
	}
	return ""
}

func (x *TLSConfig) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

func (x *TLSConfig) GetCaFile() string {
	if x != nil {
		return x.CaFile
	}
	return ""
}

func (x *TLSConfig) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *TLSConfig) GetInsecureSkipVerify() bool {
	if x != nil {
		return x.InsecureSkipVerify
	}
	return false
}

func (x *TLSConfig) GetMinVersion() uint32 {
	if x != nil {
		return x.MinVersion
	}
	return 0
}

func (x *TLSConfig) GetMaxVersion() uint32 {
	if x != nil {
		return x.MaxVersion
	}
	return 0
}

func (x *TLSConfig) GetClientAuth() int32 {
	if x != nil {
		return x.ClientAuth
	}
	return 0
}

func (x *TLSConfig) GetCipherSuites() string {
	if x != nil {
		return x.CipherSuites
	}
	return ""
}

func (x *TLSConfig) GetCipherSuitesTls13() string {
	if x != nil {
		return x.CipherSuitesTls13
	}
	return ""
}

func (x *TLSConfig) GetEnableAlpn() bool {
	if x != nil {
		return x.EnableAlpn
	}
	return false
}

func (x *TLSConfig) GetClientCertType() string {
	if x != nil {
		return x.ClientCertType
	}
	return ""
}

func (x *TLSConfig) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *TLSConfig) GetKeyPassword() string {
	if x != nil {
		return x.KeyPassword
	}
	return ""
}

func (x *TLSConfig) GetTlsAuthUsername() string {
	if x != nil {
		return x.TlsAuthUsername
	}
	return ""
}

func (x *TLSConfig) GetTlsAuthPassword() string {
	if x != nil {
		return x.TlsAuthPassword
	}
	return ""
}

// AuthConfig defines authentication configuration
type AuthConfig struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Token                string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                                             // Auth token
	TokenRefreshInterval *durationpb.Duration   `protobuf:"bytes,2,opt,name=token_refresh_interval,json=tokenRefreshInterval,proto3" json:"token_refresh_interval,omitempty"` // Token refresh interval
	Username             string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`                                                       // Username for authentication
	Password             string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`                                                       // Password for authentication
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AuthConfig) Reset() {
	*x = AuthConfig{}
	mi := &file_atframe_etcd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthConfig) ProtoMessage() {}

func (x *AuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_atframe_etcd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthConfig.ProtoReflect.Descriptor instead.
func (*AuthConfig) Descriptor() ([]byte, []int) {
	return file_atframe_etcd_proto_rawDescGZIP(), []int{2}
}

func (x *AuthConfig) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthConfig) GetTokenRefreshInterval() *durationpb.Duration {
	if x != nil {
		return x.TokenRefreshInterval
	}
	return nil
}

func (x *AuthConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// EtcdClusterConf defines the configuration for connecting to an etcd cluster
type EtcdClusterConf struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Endpoints   []string               `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`                        // List of etcd endpoints (host:port)
	DialTimeout *durationpb.Duration   `protobuf:"bytes,2,opt,name=dial_timeout,json=dialTimeout,proto3" json:"dial_timeout,omitempty"` // Connection dial timeout
	Tls         *TLSConfig             `protobuf:"bytes,3,opt,name=tls,proto3" json:"tls,omitempty"`                                    // TLS configuration for etcd connection
	// ProxyConfig and DNSConfig removed; not supported in clientv3
	Auth          *AuthConfig  `protobuf:"bytes,6,opt,name=auth,proto3" json:"auth,omitempty"`                             // Authentication configuration
	Retry         *RetryConfig `protobuf:"bytes,7,opt,name=retry,proto3" json:"retry,omitempty"`                           // Retry policy configuration
	DebugMode     bool         `protobuf:"varint,8,opt,name=debug_mode,json=debugMode,proto3" json:"debug_mode,omitempty"` // Enable debug mode (verbose logging)
	UserAgent     string       `protobuf:"bytes,9,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`  // Custom user agent string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtcdClusterConf) Reset() {
	*x = EtcdClusterConf{}
	mi := &file_atframe_etcd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtcdClusterConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtcdClusterConf) ProtoMessage() {}

func (x *EtcdClusterConf) ProtoReflect() protoreflect.Message {
	mi := &file_atframe_etcd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtcdClusterConf.ProtoReflect.Descriptor instead.
func (*EtcdClusterConf) Descriptor() ([]byte, []int) {
	return file_atframe_etcd_proto_rawDescGZIP(), []int{3}
}

func (x *EtcdClusterConf) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *EtcdClusterConf) GetDialTimeout() *durationpb.Duration {
	if x != nil {
		return x.DialTimeout
	}
	return nil
}

func (x *EtcdClusterConf) GetTls() *TLSConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *EtcdClusterConf) GetAuth() *AuthConfig {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *EtcdClusterConf) GetRetry() *RetryConfig {
	if x != nil {
		return x.Retry
	}
	return nil
}

func (x *EtcdClusterConf) GetDebugMode() bool {
	if x != nil {
		return x.DebugMode
	}
	return false
}

func (x *EtcdClusterConf) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

// EtcdResponseHeader represents etcd response metadata
type EtcdResponseHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     uint64                 `protobuf:"varint,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	MemberId      uint64                 `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Revision      int64                  `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	RaftTerm      uint64                 `protobuf:"varint,4,opt,name=raft_term,json=raftTerm,proto3" json:"raft_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtcdResponseHeader) Reset() {
	*x = EtcdResponseHeader{}
	mi := &file_atframe_etcd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtcdResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtcdResponseHeader) ProtoMessage() {}

func (x *EtcdResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_atframe_etcd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtcdResponseHeader.ProtoReflect.Descriptor instead.
func (*EtcdResponseHeader) Descriptor() ([]byte, []int) {
	return file_atframe_etcd_proto_rawDescGZIP(), []int{4}
}

func (x *EtcdResponseHeader) GetClusterId() uint64 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

func (x *EtcdResponseHeader) GetMemberId() uint64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *EtcdResponseHeader) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *EtcdResponseHeader) GetRaftTerm() uint64 {
	if x != nil {
		return x.RaftTerm
	}
	return 0
}

// EtcdKeyValue represents a key-value pair in etcd
type EtcdKeyValue struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Key            []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value          []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	CreateRevision int64                  `protobuf:"varint,3,opt,name=create_revision,json=createRevision,proto3" json:"create_revision,omitempty"`
	ModRevision    int64                  `protobuf:"varint,4,opt,name=mod_revision,json=modRevision,proto3" json:"mod_revision,omitempty"`
	Version        int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Lease          int64                  `protobuf:"varint,6,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EtcdKeyValue) Reset() {
	*x = EtcdKeyValue{}
	mi := &file_atframe_etcd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtcdKeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtcdKeyValue) ProtoMessage() {}

func (x *EtcdKeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_atframe_etcd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtcdKeyValue.ProtoReflect.Descriptor instead.
func (*EtcdKeyValue) Descriptor() ([]byte, []int) {
	return file_atframe_etcd_proto_rawDescGZIP(), []int{5}
}

func (x *EtcdKeyValue) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *EtcdKeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *EtcdKeyValue) GetCreateRevision() int64 {
	if x != nil {
		return x.CreateRevision
	}
	return 0
}

func (x *EtcdKeyValue) GetModRevision() int64 {
	if x != nil {
		return x.ModRevision
	}
	return 0
}

func (x *EtcdKeyValue) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *EtcdKeyValue) GetLease() int64 {
	if x != nil {
		return x.Lease
	}
	return 0
}

// EtcdWatchEvent represents a watch event
type EtcdWatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EtcdWatchEventType     `protobuf:"varint,1,opt,name=type,proto3,enum=atframework.etcd.EtcdWatchEventType" json:"type,omitempty"`
	Kv            *EtcdKeyValue          `protobuf:"bytes,2,opt,name=kv,proto3" json:"kv,omitempty"`
	PrevKv        *EtcdKeyValue          `protobuf:"bytes,3,opt,name=prev_kv,json=prevKv,proto3" json:"prev_kv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtcdWatchEvent) Reset() {
	*x = EtcdWatchEvent{}
	mi := &file_atframe_etcd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtcdWatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtcdWatchEvent) ProtoMessage() {}

func (x *EtcdWatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_atframe_etcd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtcdWatchEvent.ProtoReflect.Descriptor instead.
func (*EtcdWatchEvent) Descriptor() ([]byte, []int) {
	return file_atframe_etcd_proto_rawDescGZIP(), []int{6}
}

func (x *EtcdWatchEvent) GetType() EtcdWatchEventType {
	if x != nil {
		return x.Type
	}
	return EtcdWatchEventType_ETCD_WATCH_EVENT_TYPE_UNSPECIFIED
}

func (x *EtcdWatchEvent) GetKv() *EtcdKeyValue {
	if x != nil {
		return x.Kv
	}
	return nil
}

func (x *EtcdWatchEvent) GetPrevKv() *EtcdKeyValue {
	if x != nil {
		return x.PrevKv
	}
	return nil
}

// EtcdArea represents service area information (region, district, zone)
// Mirrors C++ atapp_area for cross-language compatibility
type EtcdArea struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	District      string                 `protobuf:"bytes,2,opt,name=district,proto3" json:"district,omitempty"`
	ZoneId        uint32                 `protobuf:"varint,3,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtcdArea) Reset() {
	*x = EtcdArea{}
	mi := &file_atframe_etcd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtcdArea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtcdArea) ProtoMessage() {}

func (x *EtcdArea) ProtoReflect() protoreflect.Message {
	mi := &file_atframe_etcd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtcdArea.ProtoReflect.Descriptor instead.
func (*EtcdArea) Descriptor() ([]byte, []int) {
	return file_atframe_etcd_proto_rawDescGZIP(), []int{7}
}

func (x *EtcdArea) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *EtcdArea) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *EtcdArea) GetZoneId() uint32 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

// EtcdMetadata represents service metadata with labels
// Mirrors C++ atapp_metadata for cross-language compatibility
type EtcdMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Name          string                 `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	NamespaceName string                 `protobuf:"bytes,12,opt,name=namespace_name,json=namespaceName,proto3" json:"namespace_name,omitempty"`
	Uid           string                 `protobuf:"bytes,13,opt,name=uid,proto3" json:"uid,omitempty"`
	ServiceSubset string                 `protobuf:"bytes,23,opt,name=service_subset,json=serviceSubset,proto3" json:"service_subset,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,24,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtcdMetadata) Reset() {
	*x = EtcdMetadata{}
	mi := &file_atframe_etcd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtcdMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtcdMetadata) ProtoMessage() {}

func (x *EtcdMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_atframe_etcd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtcdMetadata.ProtoReflect.Descriptor instead.
func (*EtcdMetadata) Descriptor() ([]byte, []int) {
	return file_atframe_etcd_proto_rawDescGZIP(), []int{8}
}

func (x *EtcdMetadata) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *EtcdMetadata) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *EtcdMetadata) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *EtcdMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EtcdMetadata) GetNamespaceName() string {
	if x != nil {
		return x.NamespaceName
	}
	return ""
}

func (x *EtcdMetadata) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *EtcdMetadata) GetServiceSubset() string {
	if x != nil {
		return x.ServiceSubset
	}
	return ""
}

func (x *EtcdMetadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// EtcdGateway represents a service gateway entry point
// Mirrors C++ atapp_gateway for cross-language compatibility
type EtcdGateway struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Address         string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	MatchHosts      []string               `protobuf:"bytes,11,rep,name=match_hosts,json=matchHosts,proto3" json:"match_hosts,omitempty"`                                                                              // match hostname with "In" operator
	MatchNamespaces []string               `protobuf:"bytes,21,rep,name=match_namespaces,json=matchNamespaces,proto3" json:"match_namespaces,omitempty"`                                                               // match metadata.namespace_name with "In" operator
	MatchLabels     map[string]string      `protobuf:"bytes,22,rep,name=match_labels,json=matchLabels,proto3" json:"match_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // match all labels in metadata
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EtcdGateway) Reset() {
	*x = EtcdGateway{}
	mi := &file_atframe_etcd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtcdGateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtcdGateway) ProtoMessage() {}

func (x *EtcdGateway) ProtoReflect() protoreflect.Message {
	mi := &file_atframe_etcd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtcdGateway.ProtoReflect.Descriptor instead.
func (*EtcdGateway) Descriptor() ([]byte, []int) {
	return file_atframe_etcd_proto_rawDescGZIP(), []int{9}
}

func (x *EtcdGateway) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *EtcdGateway) GetMatchHosts() []string {
	if x != nil {
		return x.MatchHosts
	}
	return nil
}

func (x *EtcdGateway) GetMatchNamespaces() []string {
	if x != nil {
		return x.MatchNamespaces
	}
	return nil
}

func (x *EtcdGateway) GetMatchLabels() map[string]string {
	if x != nil {
		return x.MatchLabels
	}
	return nil
}

// EtcdDiscoveryNode represents a discovered service node
// This is the main data structure stored in etcd for service instances
// Maps to C++ atapp_discovery from atapp_conf.proto
// Note: Use the AtappDiscovery type from atapp_conf.proto for actual service registration
// This message is kept for documentation and etcd-specific structure understanding
type EtcdDiscoveryNode struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   // Unique numeric ID
	Name       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                // Unique string name
	Hostname   string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`                        // Hostname of the service instance
	Pid        int32                  `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`                                 // Process ID
	Listen     []string               `protobuf:"bytes,5,rep,name=listen,proto3" json:"listen,omitempty"`                            // Listen addresses (e.g., ["192.168.1.1:8080"])
	HashCode   string                 `protobuf:"bytes,6,opt,name=hash_code,json=hashCode,proto3" json:"hash_code,omitempty"`        // Hash code for consistent hashing
	TypeId     uint64                 `protobuf:"varint,7,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`             // Service type ID
	TypeName   string                 `protobuf:"bytes,8,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`        // Service type name
	Area       *EtcdArea              `protobuf:"bytes,9,opt,name=area,proto3" json:"area,omitempty"`                                // Service area (region, district, zone)
	Version    string                 `protobuf:"bytes,10,opt,name=version,proto3" json:"version,omitempty"`                         // Service version
	CustomData string                 `protobuf:"bytes,11,opt,name=custom_data,json=customData,proto3" json:"custom_data,omitempty"` // Custom data field
	Identity   string                 `protobuf:"bytes,12,opt,name=identity,proto3" json:"identity,omitempty"`                       // Service identity/instance identifier
	Gateways   []*EtcdGateway         `protobuf:"bytes,13,rep,name=gateways,proto3" json:"gateways,omitempty"`                       // Service gateways
	Metadata   *EtcdMetadata          `protobuf:"bytes,14,opt,name=metadata,proto3" json:"metadata,omitempty"`                       // Service metadata with labels
	// Etcd versioning information
	CreateRevision uint64 `protobuf:"varint,15,opt,name=create_revision,json=createRevision,proto3" json:"create_revision,omitempty"` // etcd create revision (for tracking)
	ModRevision    uint64 `protobuf:"varint,16,opt,name=mod_revision,json=modRevision,proto3" json:"mod_revision,omitempty"`          // etcd mod revision (for tracking)
	VersionNum     uint64 `protobuf:"varint,17,opt,name=version_num,json=versionNum,proto3" json:"version_num,omitempty"`             // Key version in etcd
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EtcdDiscoveryNode) Reset() {
	*x = EtcdDiscoveryNode{}
	mi := &file_atframe_etcd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtcdDiscoveryNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtcdDiscoveryNode) ProtoMessage() {}

func (x *EtcdDiscoveryNode) ProtoReflect() protoreflect.Message {
	mi := &file_atframe_etcd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtcdDiscoveryNode.ProtoReflect.Descriptor instead.
func (*EtcdDiscoveryNode) Descriptor() ([]byte, []int) {
	return file_atframe_etcd_proto_rawDescGZIP(), []int{10}
}

func (x *EtcdDiscoveryNode) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EtcdDiscoveryNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EtcdDiscoveryNode) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EtcdDiscoveryNode) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *EtcdDiscoveryNode) GetListen() []string {
	if x != nil {
		return x.Listen
	}
	return nil
}

func (x *EtcdDiscoveryNode) GetHashCode() string {
	if x != nil {
		return x.HashCode
	}
	return ""
}

func (x *EtcdDiscoveryNode) GetTypeId() uint64 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *EtcdDiscoveryNode) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *EtcdDiscoveryNode) GetArea() *EtcdArea {
	if x != nil {
		return x.Area
	}
	return nil
}

func (x *EtcdDiscoveryNode) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *EtcdDiscoveryNode) GetCustomData() string {
	if x != nil {
		return x.CustomData
	}
	return ""
}

func (x *EtcdDiscoveryNode) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *EtcdDiscoveryNode) GetGateways() []*EtcdGateway {
	if x != nil {
		return x.Gateways
	}
	return nil
}

func (x *EtcdDiscoveryNode) GetMetadata() *EtcdMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EtcdDiscoveryNode) GetCreateRevision() uint64 {
	if x != nil {
		return x.CreateRevision
	}
	return 0
}

func (x *EtcdDiscoveryNode) GetModRevision() uint64 {
	if x != nil {
		return x.ModRevision
	}
	return 0
}

func (x *EtcdDiscoveryNode) GetVersionNum() uint64 {
	if x != nil {
		return x.VersionNum
	}
	return 0
}

var File_atframe_etcd_proto protoreflect.FileDescriptor

const file_atframe_etcd_proto_rawDesc = "" +
	"\n" +
	"\x12atframe/etcd.proto\x12\x10atframework.etcd\x1a\x1egoogle/protobuf/duration.proto\"\xeb\x01\n" +
	"\vRetryConfig\x12\x1f\n" +
	"\vmax_retries\x18\x01 \x01(\x05R\n" +
	"maxRetries\x12D\n" +
	"\x10initial_interval\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0finitialInterval\x12<\n" +
	"\fmax_interval\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vmaxInterval\x127\n" +
	"\abackoff\x18\x04 \x01(\x0e2\x1d.atframework.etcd.BackoffTypeR\abackoff\"\xe2\x04\n" +
	"\tTLSConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1b\n" +
	"\tcert_file\x18\x02 \x01(\tR\bcertFile\x12\x19\n" +
	"\bkey_file\x18\x03 \x01(\tR\akeyFile\x12\x17\n" +
	"\aca_file\x18\x04 \x01(\tR\x06caFile\x12\x1f\n" +
	"\vserver_name\x18\x05 \x01(\tR\n" +
	"serverName\x120\n" +
	"\x14insecure_skip_verify\x18\x06 \x01(\bR\x12insecureSkipVerify\x12\x1f\n" +
	"\vmin_version\x18\a \x01(\rR\n" +
	"minVersion\x12\x1f\n" +
	"\vmax_version\x18\b \x01(\rR\n" +
	"maxVersion\x12\x1f\n" +
	"\vclient_auth\x18\t \x01(\x05R\n" +
	"clientAuth\x12#\n" +
	"\rcipher_suites\x18\n" +
	" \x01(\tR\fcipherSuites\x12.\n" +
	"\x13cipher_suites_tls13\x18\v \x01(\tR\x11cipherSuitesTls13\x12\x1f\n" +
	"\venable_alpn\x18\f \x01(\bR\n" +
	"enableAlpn\x12(\n" +
	"\x10client_cert_type\x18\r \x01(\tR\x0eclientCertType\x12\x19\n" +
	"\bkey_type\x18\x0e \x01(\tR\akeyType\x12!\n" +
	"\fkey_password\x18\x0f \x01(\tR\vkeyPassword\x12*\n" +
	"\x11tls_auth_username\x18\x10 \x01(\tR\x0ftlsAuthUsername\x12*\n" +
	"\x11tls_auth_password\x18\x11 \x01(\tR\x0ftlsAuthPassword\"\xab\x01\n" +
	"\n" +
	"AuthConfig\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12O\n" +
	"\x16token_refresh_interval\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x14tokenRefreshInterval\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"\xc1\x02\n" +
	"\x0fEtcdClusterConf\x12\x1c\n" +
	"\tendpoints\x18\x01 \x03(\tR\tendpoints\x12<\n" +
	"\fdial_timeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\vdialTimeout\x12-\n" +
	"\x03tls\x18\x03 \x01(\v2\x1b.atframework.etcd.TLSConfigR\x03tls\x120\n" +
	"\x04auth\x18\x06 \x01(\v2\x1c.atframework.etcd.AuthConfigR\x04auth\x123\n" +
	"\x05retry\x18\a \x01(\v2\x1d.atframework.etcd.RetryConfigR\x05retry\x12\x1d\n" +
	"\n" +
	"debug_mode\x18\b \x01(\bR\tdebugMode\x12\x1d\n" +
	"\n" +
	"user_agent\x18\t \x01(\tR\tuserAgent\"\x89\x01\n" +
	"\x12EtcdResponseHeader\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\x04R\tclusterId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\x04R\bmemberId\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x03R\brevision\x12\x1b\n" +
	"\traft_term\x18\x04 \x01(\x04R\braftTerm\"\xb2\x01\n" +
	"\fEtcdKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12'\n" +
	"\x0fcreate_revision\x18\x03 \x01(\x03R\x0ecreateRevision\x12!\n" +
	"\fmod_revision\x18\x04 \x01(\x03R\vmodRevision\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\x12\x14\n" +
	"\x05lease\x18\x06 \x01(\x03R\x05lease\"\xb3\x01\n" +
	"\x0eEtcdWatchEvent\x128\n" +
	"\x04type\x18\x01 \x01(\x0e2$.atframework.etcd.EtcdWatchEventTypeR\x04type\x12.\n" +
	"\x02kv\x18\x02 \x01(\v2\x1e.atframework.etcd.EtcdKeyValueR\x02kv\x127\n" +
	"\aprev_kv\x18\x03 \x01(\v2\x1e.atframework.etcd.EtcdKeyValueR\x06prevKv\"W\n" +
	"\bEtcdArea\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x1a\n" +
	"\bdistrict\x18\x02 \x01(\tR\bdistrict\x12\x17\n" +
	"\azone_id\x18\x03 \x01(\rR\x06zoneId\"\xcc\x02\n" +
	"\fEtcdMetadata\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x12\n" +
	"\x04name\x18\v \x01(\tR\x04name\x12%\n" +
	"\x0enamespace_name\x18\f \x01(\tR\rnamespaceName\x12\x10\n" +
	"\x03uid\x18\r \x01(\tR\x03uid\x12%\n" +
	"\x0eservice_subset\x18\x17 \x01(\tR\rserviceSubset\x12B\n" +
	"\x06labels\x18\x18 \x03(\v2*.atframework.etcd.EtcdMetadata.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x02\n" +
	"\vEtcdGateway\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1f\n" +
	"\vmatch_hosts\x18\v \x03(\tR\n" +
	"matchHosts\x12)\n" +
	"\x10match_namespaces\x18\x15 \x03(\tR\x0fmatchNamespaces\x12Q\n" +
	"\fmatch_labels\x18\x16 \x03(\v2..atframework.etcd.EtcdGateway.MatchLabelsEntryR\vmatchLabels\x1a>\n" +
	"\x10MatchLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbb\x04\n" +
	"\x11EtcdDiscoveryNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\x05R\x03pid\x12\x16\n" +
	"\x06listen\x18\x05 \x03(\tR\x06listen\x12\x1b\n" +
	"\thash_code\x18\x06 \x01(\tR\bhashCode\x12\x17\n" +
	"\atype_id\x18\a \x01(\x04R\x06typeId\x12\x1b\n" +
	"\ttype_name\x18\b \x01(\tR\btypeName\x12.\n" +
	"\x04area\x18\t \x01(\v2\x1a.atframework.etcd.EtcdAreaR\x04area\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\tR\aversion\x12\x1f\n" +
	"\vcustom_data\x18\v \x01(\tR\n" +
	"customData\x12\x1a\n" +
	"\bidentity\x18\f \x01(\tR\bidentity\x129\n" +
	"\bgateways\x18\r \x03(\v2\x1d.atframework.etcd.EtcdGatewayR\bgateways\x12:\n" +
	"\bmetadata\x18\x0e \x01(\v2\x1e.atframework.etcd.EtcdMetadataR\bmetadata\x12'\n" +
	"\x0fcreate_revision\x18\x0f \x01(\x04R\x0ecreateRevision\x12!\n" +
	"\fmod_revision\x18\x10 \x01(\x04R\vmodRevision\x12\x1f\n" +
	"\vversion_num\x18\x11 \x01(\x04R\n" +
	"versionNum*k\n" +
	"\vBackoffType\x12\x1c\n" +
	"\x18BACKOFF_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rBACKOFF_FIXED\x10\x01\x12\x12\n" +
	"\x0eBACKOFF_LINEAR\x10\x02\x12\x17\n" +
	"\x13BACKOFF_EXPONENTIAL\x10\x03*r\n" +
	"\x12EtcdWatchEventType\x12%\n" +
	"!ETCD_WATCH_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ETCD_WATCH_EVENT_PUT\x10\x01\x12\x1b\n" +
	"\x17ETCD_WATCH_EVENT_DELETE\x10\x02*\xad\x02\n" +
	"\x0eEtcdSearchMode\x12\x18\n" +
	"\x14ETCD_SEARCH_MODE_ALL\x10\x00\x12\x1c\n" +
	"\x18ETCD_SEARCH_MODE_COMPACT\x10\x01\x12 \n" +
	"\x1cETCD_SEARCH_MODE_UNIQUE_NODE\x10\x02\x12(\n" +
	"$ETCD_SEARCH_MODE_COMPACT_UNIQUE_NODE\x10\x03\x12\x1e\n" +
	"\x1aETCD_SEARCH_MODE_NEXT_NODE\x10\x04\x12!\n" +
	"\x1dETCD_SEARCH_MODE_NEXT_COMPACT\x10\x05\x12%\n" +
	"!ETCD_SEARCH_MODE_NEXT_UNIQUE_NODE\x10\x06\x12-\n" +
	")ETCD_SEARCH_MODE_NEXT_COMPACT_UNIQUE_NODE\x10\aB$Z\"service_discovery/protocol;atframeb\x06proto3"

var (
	file_atframe_etcd_proto_rawDescOnce sync.Once
	file_atframe_etcd_proto_rawDescData []byte
)

func file_atframe_etcd_proto_rawDescGZIP() []byte {
	file_atframe_etcd_proto_rawDescOnce.Do(func() {
		file_atframe_etcd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atframe_etcd_proto_rawDesc), len(file_atframe_etcd_proto_rawDesc)))
	})
	return file_atframe_etcd_proto_rawDescData
}

var file_atframe_etcd_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_atframe_etcd_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_atframe_etcd_proto_goTypes = []any{
	(BackoffType)(0),            // 0: atframework.etcd.BackoffType
	(EtcdWatchEventType)(0),     // 1: atframework.etcd.EtcdWatchEventType
	(EtcdSearchMode)(0),         // 2: atframework.etcd.EtcdSearchMode
	(*RetryConfig)(nil),         // 3: atframework.etcd.RetryConfig
	(*TLSConfig)(nil),           // 4: atframework.etcd.TLSConfig
	(*AuthConfig)(nil),          // 5: atframework.etcd.AuthConfig
	(*EtcdClusterConf)(nil),     // 6: atframework.etcd.EtcdClusterConf
	(*EtcdResponseHeader)(nil),  // 7: atframework.etcd.EtcdResponseHeader
	(*EtcdKeyValue)(nil),        // 8: atframework.etcd.EtcdKeyValue
	(*EtcdWatchEvent)(nil),      // 9: atframework.etcd.EtcdWatchEvent
	(*EtcdArea)(nil),            // 10: atframework.etcd.EtcdArea
	(*EtcdMetadata)(nil),        // 11: atframework.etcd.EtcdMetadata
	(*EtcdGateway)(nil),         // 12: atframework.etcd.EtcdGateway
	(*EtcdDiscoveryNode)(nil),   // 13: atframework.etcd.EtcdDiscoveryNode
	nil,                         // 14: atframework.etcd.EtcdMetadata.LabelsEntry
	nil,                         // 15: atframework.etcd.EtcdGateway.MatchLabelsEntry
	(*durationpb.Duration)(nil), // 16: google.protobuf.Duration
}
var file_atframe_etcd_proto_depIdxs = []int32{
	16, // 0: atframework.etcd.RetryConfig.initial_interval:type_name -> google.protobuf.Duration
	16, // 1: atframework.etcd.RetryConfig.max_interval:type_name -> google.protobuf.Duration
	0,  // 2: atframework.etcd.RetryConfig.backoff:type_name -> atframework.etcd.BackoffType
	16, // 3: atframework.etcd.AuthConfig.token_refresh_interval:type_name -> google.protobuf.Duration
	16, // 4: atframework.etcd.EtcdClusterConf.dial_timeout:type_name -> google.protobuf.Duration
	4,  // 5: atframework.etcd.EtcdClusterConf.tls:type_name -> atframework.etcd.TLSConfig
	5,  // 6: atframework.etcd.EtcdClusterConf.auth:type_name -> atframework.etcd.AuthConfig
	3,  // 7: atframework.etcd.EtcdClusterConf.retry:type_name -> atframework.etcd.RetryConfig
	1,  // 8: atframework.etcd.EtcdWatchEvent.type:type_name -> atframework.etcd.EtcdWatchEventType
	8,  // 9: atframework.etcd.EtcdWatchEvent.kv:type_name -> atframework.etcd.EtcdKeyValue
	8,  // 10: atframework.etcd.EtcdWatchEvent.prev_kv:type_name -> atframework.etcd.EtcdKeyValue
	14, // 11: atframework.etcd.EtcdMetadata.labels:type_name -> atframework.etcd.EtcdMetadata.LabelsEntry
	15, // 12: atframework.etcd.EtcdGateway.match_labels:type_name -> atframework.etcd.EtcdGateway.MatchLabelsEntry
	10, // 13: atframework.etcd.EtcdDiscoveryNode.area:type_name -> atframework.etcd.EtcdArea
	12, // 14: atframework.etcd.EtcdDiscoveryNode.gateways:type_name -> atframework.etcd.EtcdGateway
	11, // 15: atframework.etcd.EtcdDiscoveryNode.metadata:type_name -> atframework.etcd.EtcdMetadata
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_atframe_etcd_proto_init() }
func file_atframe_etcd_proto_init() {
	if File_atframe_etcd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atframe_etcd_proto_rawDesc), len(file_atframe_etcd_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_atframe_etcd_proto_goTypes,
		DependencyIndexes: file_atframe_etcd_proto_depIdxs,
		EnumInfos:         file_atframe_etcd_proto_enumTypes,
		MessageInfos:      file_atframe_etcd_proto_msgTypes,
	}.Build()
	File_atframe_etcd_proto = out.File
	file_atframe_etcd_proto_goTypes = nil
	file_atframe_etcd_proto_depIdxs = nil
}
